language: c
script:
  # - gcc -coverage -O0 main.c -o test
  # - gcc -o test main.c src/myLib.c -Iinc
  # - ./test
  # - gcov main.c
  - cmake -G "Unix Makefiles" .
  - make -j4
  - ./helloC
  - gcovr --version
  - gcov CMakeFiles/HelloC.dir/main.c.obj
  - gcov CMakeFiles/HelloC.dir/src/myLib.c.obj
