language: c
before_install:
  - pip install -U pip # upgrade pip
  - sudo pip install gcovr # install gcovr
script:
  - cmake -G "Unix Makefiles" .
  - make -j4
  - ./helloC  # run app
  # - ls -R   # list all with recursive view
  - gcovr -r .
  # - gcovr -r . --html --html-details -o example-html.html
  
